#!/bin/python

#Script         Ops Challenge: Class 02 - Uptime Sensor Tool Part 1 of 2
#Purpose        Ask user for number of pings needed then proceed to ping 8.8.8.8 that many times while printing a timestamp and success or failure message to the console and writing it to a log file.
#Why            Learn how to automate a script to check uptime of a certain endpoint.

import os
import time

destination_ip = "8.8.8.8"
status = ""
counter = 0
numberofpings = int(input("Enter the number of pings to make: "))

with open("ping_log.txt", "w") as file:
    while counter < numberofpings:
        response = os.system(f"ping -c 1 {destination_ip} > /dev/null 2>&1")
        if response == 0:
            status = "success"
        else:
            status = "failure"

        timestamp = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime())
        log_entry = f"{timestamp} Network {status} to {destination_ip}"
        print(log_entry)
        file.write(log_entry + "\n")

        counter += 1
        time.sleep(2)
